# Generated by Django 4.2 on 2023-04-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0007_workoutexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExerciseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercise_details', to='workoutbuddy_api.workoutexercise')),
            ],
        ),
    ]
