# Generated by Django 4.2 on 2023-04-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0008_workoutexercisedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=None),
        ),
    ]
