# Generated by Django 4.2 on 2023-04-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0010_alter_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='gifs/'),
        ),
    ]
