# Generated by Django 4.2 on 2023-04-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0011_exercise_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='gif',
        ),
    ]
