# Generated by Django 4.2 on 2023-04-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0013_alter_exercise_user_alter_workout_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='photo_url',
            field=models.CharField(default='a string', max_length=500),
        ),
    ]
