# Generated by Django 4.2 on 2023-04-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0014_exercise_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('Barbell', 'Barbell'), ('Dumbbell', 'Dumbbell'), ('Machine', 'Machine'), ('Bodyweight', 'Bodyweight'), ('Cardio', 'Cardio'), ('Other', 'Other')], max_length=150),
        ),
    ]
