# Generated by Django 4.2 on 2023-04-13 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0016_alter_exercise_body_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date_completed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
