# Generated by Django 4.2 on 2023-04-14 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0018_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date_completed',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
