# Generated by Django 4.2 on 2023-04-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0021_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
