# Generated by Django 4.2 on 2023-04-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0023_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='start_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weight',
            name='current_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weight',
            name='goal_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
