# Generated by Django 4.2 on 2023-04-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbuddy_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
